[package]
name = "particle-life"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
log = "0.4.22"
macroquad = { version = "0.4.13", features = ["glam-serde"] }
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.3"
