[package]
name = "particle-life"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
fern = "0.7.0"
humantime = "2.1.0"
log = "0.4.22"
macroquad = "0.4.13"
rand = "0.8.5"
rayon = "1.10.0"
serde = "1.0.215"
serde_json = "1.0.133"
thiserror = "2.0.3"
